"""initial schema

Revision ID: 4444ad49784f
Revises: 
Create Date: 2026-09-03 07:48:52.917678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4444ad49784f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_config',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_type', sa.String(length=8), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("value_type IN ('float', 'int', 'str', 'bool')", name='ck_app_config_type'),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('earnings_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('session', sa.String(length=16), nullable=True),
    sa.Column('eps_estimate', sa.Float(), nullable=True),
    sa.Column('revenue_estimate', sa.Float(), nullable=True),
    sa.Column('week_of', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=32), server_default=sa.text("'Finnhub'"), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("session IN ('BMO', 'AMC', 'DMH', 'UNKNOWN')", name='ck_earnings_events_session'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_date', 'symbol', name='uq_earnings_events_date_symbol')
    )
    op.create_index('ix_earnings_date', 'earnings_events', ['report_date'], unique=False)
    op.create_table('economic_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_time_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('country', sa.String(length=8), nullable=False),
    sa.Column('event_name', sa.String(length=255), nullable=False),
    sa.Column('importance', sa.String(length=16), nullable=True),
    sa.Column('actual_value', sa.Text(), nullable=True),
    sa.Column('forecast_value', sa.Text(), nullable=True),
    sa.Column('previous_value', sa.Text(), nullable=True),
    sa.Column('week_of', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=32), server_default=sa.text("'FMP'"), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("importance IN ('Low', 'Medium', 'High')", name='ck_economic_events_importance'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_date', 'country', 'event_name', name='uq_economic_events_date_country_name')
    )
    op.create_index('ix_econ_events_date', 'economic_events', ['event_date'], unique=False)
    op.create_index('ix_econ_events_week', 'economic_events', ['week_of'], unique=False)
    op.create_table('job_run_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_name', sa.String(length=32), nullable=False),
    sa.Column('scheduled_for_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('retry_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.CheckConstraint("job_name IN ('weekly_ingestion', 'daily_news_synthesis', 'closing_check')", name='ck_job_run_log_name'),
    sa.CheckConstraint("status IN ('SUCCESS', 'PARTIAL', 'FAILED', 'SKIPPED', 'RUNNING')", name='ck_job_run_log_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_log_name_time', 'job_run_log', ['job_name', 'started_at_utc'], unique=False)
    op.create_table('market_data_snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('snapshot_type', sa.String(length=16), nullable=False),
    sa.Column('dxy', sa.Float(), nullable=True),
    sa.Column('us10y_yield', sa.Float(), nullable=True),
    sa.Column('vix', sa.Float(), nullable=True),
    sa.Column('nq_price', sa.Float(), nullable=True),
    sa.Column('nq_prior_close', sa.Float(), nullable=True),
    sa.Column('captured_at_utc', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(length=32), server_default=sa.text("'yfinance'"), nullable=False),
    sa.CheckConstraint("snapshot_type IN ('pre_open', 'close')", name='ck_market_snapshot_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_date', 'snapshot_type', name='uq_market_snapshot_date_type')
    )
    op.create_index('ix_market_snapshot_date', 'market_data_snapshot', ['snapshot_date'], unique=False)
    op.create_table('news_snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('topic', sa.String(length=32), server_default=sa.text("'macro'"), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('relevance_avg', sa.Float(), nullable=True),
    sa.Column('headline_count', sa.Integer(), nullable=True),
    sa.Column('primary_source', sa.String(length=32), server_default=sa.text("'alpha_vantage'"), nullable=False),
    sa.Column('supplementary_headlines_json', sa.JSON(), nullable=True),
    sa.Column('raw_payload_json', sa.JSON(), nullable=False),
    sa.Column('fetched_at_utc', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_date', 'topic', name='uq_news_snapshot_date_topic')
    )
    op.create_index('ix_news_snapshot_date', 'news_snapshot', ['snapshot_date'], unique=False)
    op.create_table('daily_forecast',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('run_started_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('run_finished_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('bias', sa.String(length=16), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('confidence_level', sa.String(length=16), nullable=True),
    sa.Column('uncertainty_source', sa.Text(), nullable=True),
    sa.Column('key_catalysts_json', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('reference_price', sa.Float(), nullable=True),
    sa.Column('reference_price_ts_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reference_price_source', sa.String(length=32), server_default=sa.text("'yfinance'"), nullable=False),
    sa.Column('reference_ticker', sa.String(length=16), server_default=sa.text("'NQ=F'"), nullable=False),
    sa.Column('model_id', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('market_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('news_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('raw_llm_response_json', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("bias IN ('Bullish', 'Bearish', 'Sideways')", name='ck_daily_forecast_bias'),
    sa.CheckConstraint("confidence_level IN ('Low', 'Medium', 'High')", name='ck_daily_forecast_confidence_level'),
    sa.CheckConstraint("status IN ('SUCCESS', 'PARTIAL', 'FAILED')", name='ck_daily_forecast_status'),
    sa.CheckConstraint('confidence_score IS NULL OR confidence_score BETWEEN 0.0 AND 1.0', name='ck_daily_forecast_confidence_score'),
    sa.ForeignKeyConstraint(['market_snapshot_id'], ['market_data_snapshot.id'], ),
    sa.ForeignKeyConstraint(['news_snapshot_id'], ['news_snapshot.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('forecast_date')
    )
    op.create_index('ix_daily_forecast_date', 'daily_forecast', ['forecast_date'], unique=True)
    op.create_table('daily_result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('forecast_id', sa.Integer(), nullable=False),
    sa.Column('result_date', sa.Date(), nullable=False),
    sa.Column('closing_price', sa.Float(), nullable=True),
    sa.Column('closing_price_ts_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closing_price_source', sa.String(length=32), server_default=sa.text("'yfinance'"), nullable=False),
    sa.Column('spread_points', sa.Float(), nullable=True),
    sa.Column('spread_pct', sa.Float(), nullable=True),
    sa.Column('threshold_pct_used', sa.Float(), nullable=False),
    sa.Column('actual_direction', sa.String(length=16), nullable=True),
    sa.Column('is_success', sa.Boolean(), nullable=True),
    sa.Column('evaluated_at_utc', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.CheckConstraint("actual_direction IN ('Bullish', 'Bearish', 'Sideways', 'UNKNOWN')", name='ck_daily_result_direction'),
    sa.ForeignKeyConstraint(['forecast_id'], ['daily_forecast.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('forecast_id')
    )
    op.create_index('ix_daily_result_date', 'daily_result', ['result_date'], unique=False)
    # ### end Alembic commands ###

    # rollup_stats (SPEC.md section 1.3) — implemented as views, not a synced table.
    # NOTE: strftime('%w', ...) below is SQLite syntax (matches settings.db_url's
    # default). Porting to Postgres later requires rewriting these three views with
    # EXTRACT(DOW FROM result_date) instead, per SPEC.md section 1.3's own note —
    # not done here since this migration targets the SQLite default.
    op.execute("""
        CREATE VIEW v_success_by_weekday AS
        SELECT CAST(strftime('%w', r.result_date) AS INTEGER) AS weekday,
               COUNT(*) AS n, SUM(r.is_success) AS n_success,
               ROUND(100.0 * SUM(r.is_success) / COUNT(*), 1) AS success_pct
        FROM daily_result r WHERE r.is_success IS NOT NULL GROUP BY weekday
    """)
    op.execute("""
        CREATE VIEW v_success_by_confidence AS
        SELECT f.confidence_level, COUNT(*) AS n, SUM(r.is_success) AS n_success,
               ROUND(100.0 * SUM(r.is_success) / COUNT(*), 1) AS success_pct
        FROM daily_result r JOIN daily_forecast f ON f.id = r.forecast_id
        WHERE r.is_success IS NOT NULL GROUP BY f.confidence_level
    """)
    op.execute("""
        CREATE VIEW v_success_by_weekday_confidence AS
        SELECT CAST(strftime('%w', r.result_date) AS INTEGER) AS weekday,
               f.confidence_level, COUNT(*) AS n, SUM(r.is_success) AS n_success,
               ROUND(100.0 * SUM(r.is_success) / COUNT(*), 1) AS success_pct
        FROM daily_result r JOIN daily_forecast f ON f.id = r.forecast_id
        WHERE r.is_success IS NOT NULL GROUP BY weekday, f.confidence_level
    """)


def downgrade() -> None:
    op.execute("DROP VIEW IF EXISTS v_success_by_weekday_confidence")
    op.execute("DROP VIEW IF EXISTS v_success_by_confidence")
    op.execute("DROP VIEW IF EXISTS v_success_by_weekday")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_daily_result_date', table_name='daily_result')
    op.drop_table('daily_result')
    op.drop_index('ix_daily_forecast_date', table_name='daily_forecast')
    op.drop_table('daily_forecast')
    op.drop_index('ix_news_snapshot_date', table_name='news_snapshot')
    op.drop_table('news_snapshot')
    op.drop_index('ix_market_snapshot_date', table_name='market_data_snapshot')
    op.drop_table('market_data_snapshot')
    op.drop_index('ix_job_log_name_time', table_name='job_run_log')
    op.drop_table('job_run_log')
    op.drop_index('ix_econ_events_week', table_name='economic_events')
    op.drop_index('ix_econ_events_date', table_name='economic_events')
    op.drop_table('economic_events')
    op.drop_index('ix_earnings_date', table_name='earnings_events')
    op.drop_table('earnings_events')
    op.drop_table('app_config')
    # ### end Alembic commands ###
